version: "3"

services:
  frontend:
    build: .
    volumes:
      - .:/home/repos/Egorov-React-js-Developer-MySklad
    ports:
      - "8080"
      - "3000"
    environment:
      NODE_ENV: development